apiVersion: v1
kind: Service   
metadata:
  name: web-flask-svc
  labels:
    app: web-flask
spec:
  type: LoadBalancer #NodePort #ClusterIp
  ports:
  - port: 3000  
    targetPort: 5000
    nodePort: 30001 # we can select it. or random
  selector:
    app: web-flask
