FROM node:14

# Create app directory
WORKDIR /usr/src/app

# package-lock.json, package.json are moved to app folder via "./"
COPY ./nodejs/server/package*.json ./ 

# Downloading dependencies as apposed to package-lock.json, package.json files.
RUN npm install
# If you are building your code for production
# RUN npm ci --only=production


# copy all files into the image
COPY ./nodejs/server/ .

EXPOSE 5000

CMD ["node","app.js"]