AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for running Roman Numerals Converter Website on EC2. Roman Numerals Converter Website will be deployed on Amazon Linux 2 (XXXXXXXXXXXX) EC2 Instance with custom security group which allows http connections on port 80 and ssh port 22 from anywhere. Roman Numerals Converter Website 
  is downloaded from my Public Github repository, then deployed with Flask Framework.
  
Parameters:
  KeyPairOfFlaskServer:
    Description: Select your KeyPair!
    Type: AWS::EC2::KeyPair::KeyName
  ImageIdOfFlaskServer:
    Description: Image Id Of Flask Server
    Type: String # AWS::EC2::Image::Id
    Default: ami-05fa00d4c63e32376

#Metadata:
  
#Mappings:
  
#Conditions:
  
Resources:
  SecGroupOfFlaskServer:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH and HTTP # Required
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecGroupOfFlaskFromTagName
  FlaskServer:
    Type: AWS::EC2::Instance
    Properties:
      # AdditionalInfo: "String"
      # Affinity: "String"
      # AvailabilityZone: "String" !
      # BlockDeviceMappings:
        # BlockDeviceMappings
      # CpuOptions:
        # CoreCount: Number
        # ThreadsPerCore: Number
      # CreditSpecification:
        # CPUCredits: "Number"
      # DisableApiTermination: false
      # EbsOptimized: false
      # ElasticGpuSpecifications:
        # ElasticGpuSpecifications
      # ElasticInferenceAccelerators:
        # ElasticInferenceAccelerators
      # EnclaveOptions:
        # Enabled: false
      # HibernationOptions:
        # Configured: false
      # HostId: "String"
      # HostResourceGroupArn: "String"
      # IamInstanceProfile: "String"
      ImageId: !Ref ImageIdOfFlaskServer
      # InstanceInitiatedShutdownBehavior: "String"
      InstanceType: t2.micro
      # Ipv6AddressCount: Number
      # Ipv6Addresses:
        # Ipv6Addresses
      # KernelId: "String"
      KeyName: KeyPairOfFlaskServer
      # LaunchTemplate: !
        # LaunchTemplateId: "String"
        # LaunchTemplateName: "String"
        # Version: "String"
      # LicenseSpecifications:
        # LicenseSpecifications
      # Monitoring: String
      # NetworkInterfaces:
        # NetworkInterfaces
      # PlacementGroupName: "String"
      # PrivateDnsNameOptions:
        # EnableResourceNameDnsAAAARecord: false
        # EnableResourceNameDnsARecord: false
        # HostnameType: "String"
      # PrivateIpAddress: "false" !
      # PropagateTagsToVolumeOnCreation: String
      # RamdiskId: "String"
      SecurityGroupIds:
        - !Ref SecGroupOfFlaskServer
      # SourceDestCheck: false
      # SsmAssociations:
        # SsmAssociations
      Tags:
        - Key: Name
          Value: !Sub Web Server Of ${AWS::StackName} Stack
      # Tenancy: "String"
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update
        sudo pip3 install Flask
        sudo yum install git -y
        sudo git clone https://github.com/pol-ayt/my-projects.git
        cd /home/ec2-user/my-projects/Project-001-Roman-Numerals-Converter
        sudo python3 app.py
      # Volumes:
         # Volumes
# Transform:
  
Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt FlaskServer.PublicDnsName
    Description: Roman Numerals URL