- name: Docker install and configuration
  hosts: _development
  become: true
  roles:
    - docker
- name: postgre instance configuration
  hosts: _ansible_postgresql
  become: true
  roles:
    - postgre
- name: instance configuration
  hosts: _ansible_nodejs
  become: true
  roles:
    - nodejs
- name: instance configuration
  hosts: _ansible_react
  become: true
  roles:
    - react