apiVersion: v1
kind: Service
metadata:
  name:  svc-expose
spec:
  selector:
    app: clarus-web
  type:  NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  80
    nodePort: 30002