AWSTemplateFormatVersion: 2010-09-09
Description: |
  Later!
Parameters:
  MyKeyName:
    Description: Choose your key name!
    Type: AWS::EC2::KeyPair::KeyName
    Default: firstkey
  LatestAmiId: # Use Public Systems Manager Parameter
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  MyVPC:
    Description: Choose the VPC!
    Type: AWS::EC2::VPC::Id
    # Default: 
  DomainName:
    Type: String
    Description: Apex domain name!
  DomainPrefix:
    Type: String
    Description: Sub domain prefix!
Metadata:
  
Mappings:
  
Conditions:
  
Resources:

  SecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP and SSH! # Required
      GroupName: kitten006-sec-g
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # This matches all addresses in IPv4 address space! It is present on most hosts, directed towards a local router.
      Tags:
        - Key: Name
          Value: sec-group-22-80
      VpcId: !Ref MyVPC
  HostInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroupIds:
        - !Ref SecGroup
      UserData: 



  Route53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Comment: DNS name
      Name: !Sub '${DomainPrefix}.${DomainName}'
      Type: A
      TTL: '60'
      ResourceRecords:
        - !GetAtt HostInstance.PublicIp
        
        # - 10.1.1.2 # Not a valid IP. It belongs to a private network. Address type. IPv4. ISP.
  
Outputs:
