---
    - name: create build directory
      file:
        path: "{{ react_container }}" 
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy the client folder
      copy:
        src: client/
        dest: "{{ react_container }}"
    - name: copy the Dockerfile
      copy:
        src: Dockerfile
        dest: "{{ react_container }}"
    - name: remove {{ container_name }} container and {{ image_name }} if exists
      shell: "docker ps -q --filter 'name={{ container_name }}' && docker stop {{ container_name }} && docker rm -fv {{ container_name }} && docker image rm -f {{ image_name }} || echo 'Not Found'"
    - name: build container image
      docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ react_container }}"
        source: build
        state: present
    - name: Launch nodejs docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports: 
        - "3000:3000"
      register: container_info

    - name: print the container info
      debug:
        var: container_info